// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_Zegary)
QT_DECLARE_EXTERN_RESOURCE(qmake_Zegary)
QT_DECLARE_EXTERN_RESOURCE(Zegary_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Zegary)

class ZegaryPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    ZegaryPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Zegary)
QT_KEEP_RESOURCE(qmlcache_Zegary)
QT_KEEP_RESOURCE(qmake_Zegary)
QT_KEEP_RESOURCE(Zegary_raw_qml_0)
    }
};



#include "Zegaryplugin_ZegaryPlugin.moc"
