// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_ZegaryContent)
QT_DECLARE_EXTERN_RESOURCE(qmake_ZegaryContent)
QT_DECLARE_EXTERN_RESOURCE(ZegaryContent_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_ZegaryContent)

class ZegaryContentPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    ZegaryContentPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_ZegaryContent)
QT_KEEP_RESOURCE(qmlcache_ZegaryContent)
QT_KEEP_RESOURCE(qmake_ZegaryContent)
QT_KEEP_RESOURCE(ZegaryContent_raw_qml_0)
    }
};



#include "ZegaryContentplugin_ZegaryContentPlugin.moc"
