### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Dependencies)
add_subdirectory(ZegaryContent)
add_subdirectory(Zegary)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    componentsplugin
    designeffectsplugin
    QtQuick_Studio_LogicHelperplugin
    QtQuickUltralite_Layersplugin
    QtQuickUltralite_Extrasplugin
    QtQuick_Studio_EventSystemplugin
    QtQuick_Studio_EventSimulatorplugin
    QtQuick_Studio_Effectsplugin
    TransitionItemplugin
    io_qt_EventSimulatorplugin
    EventListplugin
    ZegaryContentplugin
    Zegaryplugin)